### PR TITLE
Add searchPublicChat to Bot API

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by levlam** [comment]
It is useless to add a method which can be called at most 200 times daily. Moreover, after the limit is exausted sending messages to a chat by username and other Bot API features dependent on usernames will stop to work.

**Comment by alexey-pelykh** [comment]
@levlam I'm not finding it as useless in a scenario when bot "listens" for all messages in the chat and primarily uses chat members to resolve any mentions (that arrive by handle, not by ID - which is a pain on its own) and someone mentions a chat/user that's not inside the given chat - how else am I supposed to resolve the ID?

**Comment by levlam** [comment]
And this can't work no matter whether the method exists or not. Bots are supposed to be able to resolve only usernames of users that they have seen.

**Comment by alexey-pelykh** [comment]
As far as I understood, it will work less than 200 times a day :D

**Comment by levlam** [comment]
Yes. And when the method will stop working, then all other username-related functionality will also be broken for 24 hours.

**Pull request closed without merging**
